revert and refactor the recursive algorithm
lgfrbcsgo/du-factory-generator pull request #28
Opened 2020-10-21 05:10 UTC by tvwenger

Reverts the recursive algorithm back the return containers. This fixes the egress error in https://github.com/lgfrbcsgo/du-factory-generator/issues/27 without any loss to generality (as far as I can tell).

2020-10-21 09:07 UTC, lgfrbcsgo requested changes
My refactoring didn't cause this issue as I didn't change the algorithm. I've added a sanity check though which made the already existing edge case apparent.

2020-10-21 11:10 UTC, lgfrbcsgo approved these changes
I am so sorry. I am not in a good mood today. You are absolutely right, that my change has introduced a bug.

2020-10-22 04:52 UTC, tvwenger commented
I changed this up a little bit. If a container will require more than 10 input links, those input links are instead split between multiple containers. The ContainerNode keeps track of it's split fraction, and uses that to correct its egress and maintain values. No other industries are allowed to draw from a split container to prevent backup in the factory (i.e. one of the split containers being used more than the others).

2020-10-22 16:27 UTC, tvwenger commented
This also fixes https://github.com/lgfrbcsgo/du-factory-generator/issues/29

2020-10-22 16:30 UTC, lgfrbcsgo approved these changes

2020-10-22 16:45 UTC, merged